# Generated by Django 4.2.2 on 2023-09-03 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=60)),
                ('account_number', models.CharField(max_length=20)),
                ('account_balance', models.IntegerField(default=10000.0)),
                ('transaction_pin', models.CharField(max_length=6)),
                ('date_opened', models.DateField(auto_now_add=True)),
                ('time_opened', models.DateTimeField(auto_now_add=True)),
                ('account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Login_form',
        ),
    ]
