# Generated by Django 4.2.2 on 2023-09-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_delete_login_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_phone',
            field=models.CharField(default='0000000000', max_length=14),
        ),
    ]
