# Generated by Django 4.2.2 on 2023-09-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='account_owner',
        ),
    ]
