# Generated by Django 4.2.2 on 2023-09-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_transactionhistory_account_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
