# Generated by Django 4.2.2 on 2023-09-24 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_delete_transactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=60)),
                ('account_number', models.CharField(max_length=20)),
                ('account_balance', models.IntegerField(default=10000.0)),
                ('time_of_transaction', models.DateTimeField(auto_now_add=True)),
                ('account_history_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_account_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=60)),
                ('account_number', models.CharField(max_length=20)),
                ('account_balance', models.IntegerField(default=10000.0)),
                ('time_of_transaction', models.DateTimeField(auto_now_add=True)),
                ('account_history_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
