# Generated by Django 4.2.2 on 2023-09-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_debithistory_credithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='credithistory',
            name='amount_credited',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='debithistory',
            name='amount_debited',
            field=models.IntegerField(default=1000),
        ),
    ]
